language: python
python:
 - "2.7"
env:
 - CFLAGS=-O0
install:
 - "uname -a"
 - "lsb_release -a"
 - "curl http://127.0.0.1:5984/"
 - "pip install -e ."
 - "pip install coverage coveralls unittest2 mock"
script: coverage run `which django-admin.py` test --settings settings --traceback couchlog
after_success:
 - coveralls
 - coverage report
services:
 - couchdb
